doctrine_migrations:
    migrations_paths:
        # Migration classes should not be application-autoloaded.
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
        'DoctrineMigrations\Security': '%kernel.project_dir%/security-migrations'
    enable_profiler: false
