services:

  backend:
    build:
      context: ../services/backend
      dockerfile: docker/php/Dockerfile

    container_name: ai-platform-backend

    expose:
      - "9000"

    volumes:
      - ../services/backend:/var/www/html

    working_dir: /var/www/html

    depends_on:
      - postgres
      - ai-orchestrator

  nginx:
    image: nginx:alpine

    container_name: ai-platform-nginx

    ports:
      - "8080:80"

    volumes:
      - ../services/backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - backend

  postgres:
    image: postgres:17

    container_name: ai-platform-postgres

    environment:
      POSTGRES_DB: ai_platform
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  ai-orchestrator:
    build:
      context: ../services/ai-orchestrator

    container_name: ai-orchestrator

    ports:
      - "3000:3000"

    volumes:
      - ../services/ai-orchestrator:/app
      - ai_orchestrator_node_modules:/app/node_modules

    working_dir: /app

    env_file:
      - ../services/ai-orchestrator/.env

    environment:
      BACKEND_URL: http://nginx

volumes:
  postgres_data:
  ai_orchestrator_node_modules: