<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260703120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add conversation, conversation_message, and proposal tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) DEFAULT NULL, company VARCHAR(255) DEFAULT NULL, state VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lead_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A8E26E955458D ON conversation (lead_id)');
        $this->addSql('CREATE TABLE conversation_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) NOT NULL, content TEXT NOT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, conversation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7A54DBD39AC039E ON conversation_message (conversation_id)');
        $this->addSql('CREATE TABLE proposal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content JSON NOT NULL, pdf_path VARCHAR(500) DEFAULT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, conversation_id INT NOT NULL, lead_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BFE59472AC039E ON proposal (conversation_id)');
        $this->addSql('CREATE INDEX IDX_BFE5947255458D ON proposal (lead_id)');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E955458D FOREIGN KEY (lead_id) REFERENCES lead (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation_message ADD CONSTRAINT FK_7A54DBD39AC039E FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE proposal ADD CONSTRAINT FK_BFE594729AC039E FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE proposal ADD CONSTRAINT FK_BFE5947255458D FOREIGN KEY (lead_id) REFERENCES lead (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E955458D');
        $this->addSql('ALTER TABLE conversation_message DROP CONSTRAINT FK_7A54DBD39AC039E');
        $this->addSql('ALTER TABLE proposal DROP CONSTRAINT FK_BFE594729AC039E');
        $this->addSql('ALTER TABLE proposal DROP CONSTRAINT FK_BFE5947255458D');
        $this->addSql('DROP TABLE proposal');
        $this->addSql('DROP TABLE conversation_message');
        $this->addSql('DROP TABLE conversation');
    }
}
